### ISSUE TITLE
Flaky test in CompactionProcessorTest

### ISSUE THREAD

**Issue by ocadaruma** [line/decaton#103]
- `CompactionProcessorTest > testOutputDelayed ` fails occasionally with following error:

```
com.linecorp.decaton.processor.processors.CompactionProcessorTest > testOutputDelayed FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at com.linecorp.decaton.processor.processors.CompactionProcessorTest.testOutputDelayed(CompactionProcessorTest.java:218)
```

**Comment by jyterencekim** [comment]
Is this test still flaky? If so, in what environment/circumstances does it fail (often)? I haven't seen it fail so far, and any additional clues would be appreciated. 🙏🏼
