### ISSUE TITLE
Closing ProcessorSubscription twice causes NPE

### ISSUE THREAD

**Issue by mauhiz** [line/decaton#58]
trace:

```
java.lang.NullPointerException: null
	at com.linecorp.decaton.processor.metrics.Metrics$AbstractMetrics.close(Metrics.java:84)
	at com.linecorp.decaton.processor.metrics.Metrics$SubscriptionMetrics.close(Metrics.java:95)
	at com.linecorp.decaton.processor.runtime.ProcessorSubscription.awaitShutdown(ProcessorSubscription.java:424)
	at com.linecorp.decaton.processor.runtime.AsyncShutdownable.close(AsyncShutdownable.java:27)
```

It looks like closed `meter` should be removed from `meters` List in `AbstractMetrics`.

**Comment by kawamuray** [comment]
> It looks like closed meter should be removed from meters List in AbstractMetrics.

Definitely, nice catch!
Do you mind submitting a PR? 
Besides, while I know `AutoClosable#close` should behave idempotently for multiple calls, just wondering how come could your subscription gets closed twice?

**Comment by mauhiz** [comment]
Calling close on a Spring managed bean
